### ISSUE TITLE
DateFormat exception

### ISSUE THREAD

**Issue by johnnyontheweb** [ixmilia/step#11]
Hello,
firts of all, my compliments for this project.

I tries to use this library, and I got a DateTime exception with a sample stp file, here's the stack:
`   in System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   in System.DateTime.Parse(String s, IFormatProvider provider, DateTimeStyles styles)
   in IxMilia.Step.Syntax.StepSyntaxExtensions.GetDateTimeValue(StepSyntax syntax)
   in IxMilia.Step.StepReader.ApplyFileName(StepSyntaxList valueList)
   in IxMilia.Step.StepReader.ApplyHeaderMacro(StepHeaderMacroSyntax macro)
   in IxMilia.Step.StepReader.ReadFile()
   in IxMilia.Step.StepFile.Load(Stream stream)`

Please find attached the file (taken from nist).
[ETABS.zip](https://github.com/ixmilia/step/files/4283266/ETABS.zip)

**Comment by brettfo** [comment]
Thanks for finding and filing an issue!

I should first mention that this library is nowhere near complete (or maybe even usable.)  Be that as it may, I've fixed the DateTime parsing issue in commit 2ed6f3fbdafe73193f38a39670526560cffd345f.
