### ISSUE TITLE
Cannot build on Windows: `MSBUILD : error MSB1008: Only one project can be specified.`

### ISSUE THREAD

**Issue by lunes-anton** [ixmilia/step#12]
I have .NET Core 3 installed:
```
> dotnet --version
3.1.101
```

When running the `build-and-test.cmd` script under windows 10 Home, version 1809, build 17763.1098, I get the following output:

```
MSBUILD : error MSB1008: Only one project can be specified.
Switch: ...\step\src\IxMilia.Step.sln

For switch syntax, type "MSBuild -help"
```

Maybe more detailed build instructions would be apreciated.

**Comment by brettfo** [comment]
Before I continue, I should mention that this repo is nowhere near complete, or maybe even usable, but I do hope it's somewhat helpful in whatever you're trying to do with it.

---

The error message seems to indicate that you're either not running `build-and-test.cmd` from the root of the repo, or you have spaces in the path.  The contents of that script are pretty straight forward, but you can try running the `dotnet` commands directly like so:

```
dotnet restore .\src\IxMilia.Step.sln
dotnet build .\src\IxMilia.Step.sln
dotnet test .\src\IxMilia.Step.sln
```

I'll update the script shortly to handle spaces in the path.
