### ISSUE TITLE
Migrate to MIT license

### ISSUE THREAD

**Issue by brettfo** [ixmilia/step#13]
I'd like to migrate this repo to be under the MIT license, but to do that I need the approval of other contributors.  If each of you agree to this, can you add a comment below indicating this?

@andreaswatch relevant commits:
- Wrong parsing result with decimals like 1.8 (3c7085b5230957f6b2123ff8e614be133ef98394)
- Resolve Problem with other DateTimeFormat (bde3a0b4509893a2e7a5d449218b5e41e44f88cc)

@jherink relevant commits:
- Corrected definition of ellipse, use axis2_placement rather than ax… (af5ae27d4853559854fccc1f16854f19f9beb939)

**Comment by jherink** [comment]
Yes I approve

**Comment by andreaswatch** [comment]
Yes I approve

jherink <notifications@github.com> schrieb am Fr. 17. Apr. 2020 um 20:02:
