### ISSUE TITLE
I got an exception while parsing STEP file

### ISSUE THREAD

**Issue by uzername** [ixmilia/step#17]
I got a step file, and I am trying to read it with this library. It opens in Inventor and in FreeCAD, so the file is okay.

![image](https://user-images.githubusercontent.com/864126/124867973-bdc19b00-dfc7-11eb-81e0-540681a83fac.png)

It is in StepBinder.cs:65, in BindRemainingValues()

**Comment by uzername** [comment]
Line #401 of my file looks like:

```
#361 = EDGE_CURVE ( 'NONE', #17298, #10171, #2644, .T. ) ;
```

Later I have such mention of 2644

```
#2644 =( BOUNDED_CURVE ( )  B_SPLINE_CURVE ( 3, ( #1562, #21152, #11366, #13008 ),
 .UNSPECIFIED., .F., .T. ) 
 B_SPLINE_CURVE_WITH_KNOTS ( ( 4, 4 ),
 ( 2.053192979712429977, 2.070202670837279157 ),
 .UNSPECIFIED. ) 
 CURVE ( )  GEOMETRIC_REPRESENTATION_ITEM ( )  RATIONAL_B_SPLINE_CURVE ( ( 1.000000000000000000, 0.9999758893459853581, 0.9999758893459853581, 1.000000000000000000 ) ) 
 REPRESENTATION_ITEM ( '' )  );
```

**Comment by uzername** [comment]
I used Master branch

**Comment by brettfo** [comment]
This library/repo is purely experimental and not ready for general use; only a few entity types are supported and `EDGE_CURVE` currently isn't one of them, as per pinned issue #15.
