### ISSUE TITLE
Difference between schema_parser and master branch

### ISSUE THREAD

**Issue by uzername** [ixmilia/step#18]
You have stated that this repository is not actively developed. I am interested in this project, so I may try and add some features to it. Or other coder. 

I'd like to know more about this project.

I see, schema_parser branch continues master branch. Which branch is better for adding support of new items - Schema parser or Master ?

**Comment by brettfo** [comment]
If you're interested in adding support for new entity types, `main` is definitely the place to do it; `schema-parser` won't be usable for quite some time.

That said, I'm not currently taking PRs into this repo, but you're more than welcome to fork it and add as you see fit.
