### ISSUE TITLE
Enumerations with underline

### ISSUE THREAD

**Issue by brookman** [IxMilia/Step#7]
STEP files generated by the "eplan" software contain underline "_" characters in enumerations. Examples:

`#6 = PRODUCT_DEFINITION_FORMATION_WITH_SPECIFIED_SOURCE('','',#7,.NOT_KNOWN.);

#6032 = B_SPLINE_CURVE_WITH_KNOTS('',1,(#6033,#6034),.UNSPECIFIED.,.F., .F.,(2,2),(-1.339260243567,0.),.PIECEWISE_BEZIER_KNOTS.);`

I'm not sure if this violates the standard, but a quick fix would be to add underlines at "StepTokenizer.cs:471" 

`var value = TakeWhile(IsUpperOrDigit); ->  var value = TakeWhile(IsUpperOrDigitOrUnderline);`

**Comment by brettfo** [comment]
Thanks for the report!  You're absolutely correct about where the issue was, so it was a quick fix.
